### ISSUE TITLE
Issue with hclust-cpp and OpenDBA

### ISSUE THREAD

**Issue by HaraldWilhelmi** [cdalitz/hclust-cpp#4]
Recently we have seen an issue with OpenDBA tests when we installed them on our systems.
The OpenDBA developers suggest that the the issue is actually located in the hclust-cpp code.
For details see:

https://github.com/nodrogluap/OpenDBA/issues/13

Any hints would be welcome.

Thanks and best regards
Harald Wilhelmi

**Comment by cdalitz** [comment]
Thanks for the information Unfortunately, the bug report at OpenDBA does not include sample data nor any hint which clustering method causes the issue.

Is it possible to provide a sample data set (data points or the distance matrix) and a small chunk of code that produces the issue?

**Comment by HaraldWilhelmi** [comment]
Just instrumented the code and I believe It got the data. To keep all dirty details in one spot I documented it here:
https://github.com/nodrogluap/OpenDBA/issues/13

**Comment by HaraldWilhelmi** [comment]
I'm pretty certain that the issue described is not related to hclust-cpp.
So I'm closing this bug.

Thanks for your help.

P.S.: May be your exception should inherit from std::exception. I believe that would
have helped to get around the "unknown exception" I have run into first in the original
issue.
